# Default values for my-website-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 339713094731.dkr.ecr.us-east-2.amazonaws.com/my-website-service
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {
    cert-manager.io/cluster-issuer: "letsencrypt-prod",
    kubernetes.io/ingress.class: "nginx",
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP",
    nginx.ingress.kubernetes.io/ssl-redirect: "true",
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true",
    nginx.ingress.kubernetes.io/use-port-in-redirects: "true",
  }
  hosts:
    - host: bricealdrich.com
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: www.bricealdrich.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: bricealdrich-tls
     hosts:
       - bricealdrich.com
   - secretName: www-bricealdrich-tls
     hosts:
       - www.bricealdrich.com

resources: {}

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

env:
  fromEmail: noreply@bricealdrich.com
  forwardEmail: hi@bricealdrich.com