name: Deploy React App to AWS
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Development Environment - PR Only
  dev-terraform-plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd infra/tf/dev
          terraform init

      - name: Terraform Plan
        id: plan
        run: |
          cd infra/tf/dev
          terraform plan -no-color -out=tfplan

  dev-terraform-apply:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [dev-terraform-plan]
    environment: dev
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init and Apply
        run: |
          cd infra/tf/dev
          terraform init
          terraform apply -auto-approve

  dev-build-and-deploy:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [dev-terraform-apply]
    environment: dev
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Application
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
        run: |
          cd infra/tf/dev
          terraform init
          export S3_BUCKET=$(terraform output -raw s3_bucket_name)
          export CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id)
          
          cd ../../..

          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile
          
          # Build the application
          yarn build
          
          aws s3 sync build/ s3://$S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

  # QA Environment - Automatic on Main
  qa-terraform-plan:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: qa
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init and Plan
        id: plan
        run: |
          cd infra/tf/qa
          terraform init
          terraform plan -no-color -out=tfplan

  qa-terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [qa-terraform-plan]
    environment: qa
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init and Apply
        run: |
          cd infra/tf/qa
          terraform init
          terraform apply -auto-approve

  qa-build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [qa-terraform-apply]
    environment: qa
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Application
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
        run: |
          cd infra/tf/qa
          terraform init
          export S3_BUCKET=$(terraform output -raw s3_bucket_name)
          export CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id)
          
          cd ../../..
          
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile
          
          # Build the application
          yarn build
          
          aws s3 sync build/ s3://$S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

  # Production Environment - Manual Approval Required
  prod-terraform-plan:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod'
    runs-on: ubuntu-latest
    needs: [qa-build-and-deploy]
    environment: prod
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init and Plan
        id: plan
        run: |
          cd infra/tf/prod
          terraform init
          terraform plan -no-color -out=tfplan

  prod-terraform-apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [prod-terraform-plan]
    environment:
      name: prod
      url: ${{ steps.get-url.outputs.url }}  # You can set this to your production URL
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init and Apply
        run: |
          cd infra/tf/prod
          terraform init
          terraform apply -auto-approve

  prod-build-and-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [prod-terraform-apply]
    environment:
      name: prod
      url: ${{ steps.get-url.outputs.url }}  # You can set this to your production URL
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Application
        env:
          NODE_OPTIONS: '--openssl-legacy-provider'
        run: |
          cd infra/tf/prod
          terraform init
          export S3_BUCKET=$(terraform output -raw s3_bucket_name)
          export CLOUDFRONT_ID=$(terraform output -raw cloudfront_distribution_id)
          
          cd ../../..
          
          rm -rf node_modules yarn.lock
          yarn install --frozen-lockfile
          
          # Build the application
          yarn build
          
          aws s3 sync build/ s3://$S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"